// Golden parity tests for Pacifica signing.
// These vectors were derived from the Python SDK during implementation and are
// now kept as direct Zig expectations so normal test runs stay self-contained.

const std = @import("std");
const testing = std.testing;
const lib = @import("lib");
const sdk = @import("sdk");
const Signer = lib.crypto.signer.Signer;
const signing = sdk.signing;

// Test keypair: seed = bytes(0..31), generated by Python's Keypair.from_seed()
const TEST_SECRET_B58 = "1GMkH3brNXiNNs1tiFZHu4yZSRrzJwxi5wB9bHFtMikjwpAW9DMZzU2Pqakc5it8X3N5vPmqdN7KF4CCUpmKhq";
const TEST_PUBKEY_B58 = "FAe4sisG95oZ42w7buUn5qEE4TAnfTTFPiguZUHmhiF";

const Vector = struct {
    name: []const u8,
    msg_type: []const u8,
    payload_json: []const u8,
    timestamp: u64,
    expiry_window: u64,
    expected_message: []const u8,
    expected_signature: []const u8,
};

const vectors = [_]Vector{
    .{
        .name = "create_order_limit_buy",
        .msg_type = "create_order",
        .payload_json =
        \\{"symbol":"BTC","price":"100000","amount":"0.1","side":"bid","tif":"GTC","reduce_only":false,"client_order_id":"12345678-1234-1234-1234-123456789abc"}
        ,
        .timestamp = 1709000000000,
        .expiry_window = 5000,
        .expected_message =
        \\{"data":{"amount":"0.1","client_order_id":"12345678-1234-1234-1234-123456789abc","price":"100000","reduce_only":false,"side":"bid","symbol":"BTC","tif":"GTC"},"expiry_window":5000,"timestamp":1709000000000,"type":"create_order"}
        ,
        .expected_signature = "Rago2y1q27gm9CJ51tVpKE85qR1wciUfRewUv9G3YSdrsXsV2ifXB8uTZNuWdR4jJx2GebzVBshv8S5Wez8fHmM",
    },
    .{
        .name = "create_market_order",
        .msg_type = "create_market_order",
        .payload_json =
        \\{"symbol":"BTC","amount":"0.1","side":"bid","slippage_percent":"0.5","reduce_only":false,"client_order_id":"12345678-1234-1234-1234-123456789abc"}
        ,
        .timestamp = 1709000000000,
        .expiry_window = 5000,
        .expected_message =
        \\{"data":{"amount":"0.1","client_order_id":"12345678-1234-1234-1234-123456789abc","reduce_only":false,"side":"bid","slippage_percent":"0.5","symbol":"BTC"},"expiry_window":5000,"timestamp":1709000000000,"type":"create_market_order"}
        ,
        .expected_signature = "3LC9HRioVnEcehMWBYt1obF2Lc9uRuc7W4FoGN3PAeejegtvAbUKQRcr855bQNRa3qUy8Cv6FUPTk7xRUafnW25j",
    },
    .{
        .name = "cancel_order",
        .msg_type = "cancel_order",
        .payload_json =
        \\{"symbol":"BTC","order_id":42069}
        ,
        .timestamp = 1709000000000,
        .expiry_window = 5000,
        .expected_message =
        \\{"data":{"order_id":42069,"symbol":"BTC"},"expiry_window":5000,"timestamp":1709000000000,"type":"cancel_order"}
        ,
        .expected_signature = "5AX8sv6kHew4UEg1WbjAYLR33kDrmsxjq3yA4YYwNYan5PA6B2h4nzzT1CAKnnTmkEsEYf1wFN2eo51D62EZyjec",
    },
    .{
        .name = "cancel_all_orders",
        .msg_type = "cancel_all_orders",
        .payload_json =
        \\{"all_symbols":true,"exclude_reduce_only":false}
        ,
        .timestamp = 1709000000000,
        .expiry_window = 5000,
        .expected_message =
        \\{"data":{"all_symbols":true,"exclude_reduce_only":false},"expiry_window":5000,"timestamp":1709000000000,"type":"cancel_all_orders"}
        ,
        .expected_signature = "5g3pFMa6VhQSAPU1cyDwDHu6p9JkaKyPRgysDfzLCTUsPxPZv4vjrjJJkDYqi2TVwtTnhT5n5KDjGPzvaFepyLGg",
    },
    .{
        .name = "update_leverage",
        .msg_type = "update_leverage",
        .payload_json =
        \\{"symbol":"BTC","leverage":42}
        ,
        .timestamp = 1709000000000,
        .expiry_window = 5000,
        .expected_message =
        \\{"data":{"leverage":42,"symbol":"BTC"},"expiry_window":5000,"timestamp":1709000000000,"type":"update_leverage"}
        ,
        .expected_signature = "5bBW2yiQQTpcZwCsqFSF9LYEFvkZwPvMYABkdf2EGWFBfE2yGxpBUxUG8A48uSfqZEoB2xhvE4uG26iizp1NT73V",
    },
    .{
        .name = "bind_agent_wallet",
        .msg_type = "bind_agent_wallet",
        .payload_json =
        \\{"agent_wallet":"AgentWalletAddress123"}
        ,
        .timestamp = 1709000000000,
        .expiry_window = 5000,
        .expected_message =
        \\{"data":{"agent_wallet":"AgentWalletAddress123"},"expiry_window":5000,"timestamp":1709000000000,"type":"bind_agent_wallet"}
        ,
        .expected_signature = "32VCTyZM33j9rNtMn6BjaPYW6wCCckTxWubxiFZF2Er2AytiUF8v9keBCMzvpNVwEGyxVLasxz3s86HGZq5TywCE",
    },
    .{
        .name = "create_order_limit_sell",
        .msg_type = "create_order",
        .payload_json =
        \\{"symbol":"ETH","price":"3400.50","amount":"1.0","side":"ask","tif":"IOC","reduce_only":true,"client_order_id":"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"}
        ,
        .timestamp = 1709000000000,
        .expiry_window = 5000,
        .expected_message =
        \\{"data":{"amount":"1.0","client_order_id":"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee","price":"3400.50","reduce_only":true,"side":"ask","symbol":"ETH","tif":"IOC"},"expiry_window":5000,"timestamp":1709000000000,"type":"create_order"}
        ,
        .expected_signature = "8X4QZG4SDbjsDcKufsWsMxphwosDPLTJqnL6EYodhGhEQbSs6GpAgUcxBQyofYLubbsVaQZSuCEBfaLTSYkz65w",
    },
    .{
        .name = "empty_payload",
        .msg_type = "list_subaccounts",
        .payload_json =
        \\{}
        ,
        .timestamp = 1709000000000,
        .expiry_window = 5000,
        .expected_message =
        \\{"data":{},"expiry_window":5000,"timestamp":1709000000000,"type":"list_subaccounts"}
        ,
        .expected_signature = "ezzY3mJWYbDvAtDWDBCez4KRLF6RZYdesPECtdCjefJV74ABv9TgWbVxnD5tx9gdRZy68EygC2viVK9CnFhvNDG",
    },
};

test "golden parity: signer loads test keypair correctly" {
    const signer = try Signer.fromBase58(TEST_SECRET_B58);
    var pub_buf: [44]u8 = undefined;
    const pub_b58 = signer.pubkeyBase58(&pub_buf);
    try testing.expectEqualStrings(TEST_PUBKEY_B58, pub_b58);
}

test "golden parity: all signing vectors match Python SDK" {
    const allocator = testing.allocator;
    const signer = try Signer.fromBase58(TEST_SECRET_B58);

    for (vectors) |v| {
        const parsed = try std.json.parseFromSlice(std.json.Value, allocator, v.payload_json, .{});
        defer parsed.deinit();

        var result = try signing.signRequest(
            allocator,
            &signer,
            v.msg_type,
            parsed.value,
            v.timestamp,
            v.expiry_window,
        );
        defer result.deinit();

        if (!std.mem.eql(u8, v.expected_message, result.message)) {
            std.debug.print("\n[FAIL] {s}: message mismatch\n  expected: {s}\n  got:      {s}\n", .{
                v.name, v.expected_message, result.message,
            });
            return error.MessageMismatch;
        }

        if (!std.mem.eql(u8, v.expected_signature, result.signature())) {
            std.debug.print("\n[FAIL] {s}: signature mismatch\n  expected: {s}\n  got:      {s}\n", .{
                v.name, v.expected_signature, result.signature(),
            });
            return error.SignatureMismatch;
        }
    }
}

test "builder_code: included in signed message for create_order" {
    const allocator = testing.allocator;
    const signer = try Signer.fromBase58(TEST_SECRET_B58);
    
    const payload_json =
        \\{"symbol":"BTC","price":"100000","amount":"0.1","side":"bid","tif":"GTC","reduce_only":false,"client_order_id":"12345678-1234-1234-1234-123456789abc","builder_code":"mybuilder"}
    ;
    const parsed = try std.json.parseFromSlice(std.json.Value, allocator, payload_json, .{});
    defer parsed.deinit();

    var result = try signing.signRequest(
        allocator,
        &signer,
        "create_order",
        parsed.value,
        1709000000000,
        5000,
    );
    defer result.deinit();

    // Verify builder_code is in the message
    try testing.expect(std.mem.indexOf(u8, result.message, "\"builder_code\":\"mybuilder\"") != null);
    
    // Verify message structure
    try testing.expect(std.mem.indexOf(u8, result.message, "\"data\":{") != null);
    try testing.expect(std.mem.indexOf(u8, result.message, "\"type\":\"create_order\"") != null);
}

test "builder_code: included in signed message for create_market_order" {
    const allocator = testing.allocator;
    const signer = try Signer.fromBase58(TEST_SECRET_B58);
    
    const payload_json =
        \\{"symbol":"ETH","amount":"2.0","side":"ask","slippage_percent":"0.5","reduce_only":false,"client_order_id":"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee","builder_code":"ABC123"}
    ;
    const parsed = try std.json.parseFromSlice(std.json.Value, allocator, payload_json, .{});
    defer parsed.deinit();

    var result = try signing.signRequest(
        allocator,
        &signer,
        "create_market_order",
        parsed.value,
        1709000000000,
        5000,
    );
    defer result.deinit();

    // Verify builder_code is in the message
    try testing.expect(std.mem.indexOf(u8, result.message, "\"builder_code\":\"ABC123\"") != null);
    try testing.expect(std.mem.indexOf(u8, result.message, "\"type\":\"create_market_order\"") != null);
}

test "builder_code: included at top level for set_position_tpsl" {
    const allocator = testing.allocator;
    const signer = try Signer.fromBase58(TEST_SECRET_B58);
    
    const payload_json =
        \\{"symbol":"BTC","side":"ask","tp_trigger":"120000","tp_limit":"120500","sl_trigger":"95000","sl_limit":"94800","builder_code":"tpslbuilder"}
    ;
    const parsed = try std.json.parseFromSlice(std.json.Value, allocator, payload_json, .{});
    defer parsed.deinit();

    var result = try signing.signRequest(
        allocator,
        &signer,
        "set_position_tpsl",
        parsed.value,
        1709000000000,
        5000,
    );
    defer result.deinit();

    // Verify builder_code is at top level in data, not nested
    try testing.expect(std.mem.indexOf(u8, result.message, "\"builder_code\":\"tpslbuilder\"") != null);
    
    // Verify TP/SL fields are also present
    try testing.expect(std.mem.indexOf(u8, result.message, "\"tp_trigger\":\"120000\"") != null);
    try testing.expect(std.mem.indexOf(u8, result.message, "\"sl_limit\":\"94800\"") != null);
}

test "builder_code: included in signed message for create_stop_order" {
    const allocator = testing.allocator;
    const signer = try Signer.fromBase58(TEST_SECRET_B58);
    
    const payload_json =
        \\{"symbol":"SOL","side":"bid","stop_price":"150","limit_price":"149.50","amount":"100","reduce_only":false,"client_order_id":"stop-12345678-1234-1234-1234-123456789abc","builder_code":"stopbuilder"}
    ;
    const parsed = try std.json.parseFromSlice(std.json.Value, allocator, payload_json, .{});
    defer parsed.deinit();

    var result = try signing.signRequest(
        allocator,
        &signer,
        "create_stop_order",
        parsed.value,
        1709000000000,
        5000,
    );
    defer result.deinit();

    // Verify builder_code is in the message
    try testing.expect(std.mem.indexOf(u8, result.message, "\"builder_code\":\"stopbuilder\"") != null);
    try testing.expect(std.mem.indexOf(u8, result.message, "\"type\":\"create_stop_order\"") != null);
}

test "builder_code: message signs successfully without builder_code" {
    const allocator = testing.allocator;
    const signer = try Signer.fromBase58(TEST_SECRET_B58);
    
    const payload_json =
        \\{"symbol":"BTC","price":"100000","amount":"0.1","side":"bid","tif":"GTC","reduce_only":false,"client_order_id":"12345678-1234-1234-1234-123456789abc"}
    ;
    const parsed = try std.json.parseFromSlice(std.json.Value, allocator, payload_json, .{});
    defer parsed.deinit();

    var result = try signing.signRequest(
        allocator,
        &signer,
        "create_order",
        parsed.value,
        1709000000000,
        5000,
    );
    defer result.deinit();

    // Verify builder_code is NOT in the message
    try testing.expect(std.mem.indexOf(u8, result.message, "builder_code") == null);
    
    // But the message should still be valid
    try testing.expect(std.mem.indexOf(u8, result.message, "\"type\":\"create_order\"") != null);
}
